### ISSUE TITLE
Not functioning 'Insert Cell below/above' and possibly other things...

### ISSUE THREAD

**Issue by misolietavec** [lgpage/nbtutor#33]
Hi, Logan,

I liked to try nbtutor with nbgrader. This is weird issue, after enabling nbtutor globally - I am unable to make anything with cells - especially create cell below current cell (by menu item `Insert -> Insert Cell Below` or by keyboard shortcut). I am sure this is nbtutor issue, because
- at another server with nbgrader (but not nbtutor enabled) it works normally
- at the server giving trouble, after disabling nbtutor, all is as it should be.

My actual software versions you can see from nbgrader issue https://github.com/jupyter/nbgrader/issues/891, which I submitted today.

Edit: link to nbgrader issue

**Comment by lgpage** [comment]
@misolietavec thank you for posting this issue. This is a known issue (see #30) that I have not gotten around to fixing yet. At the moment work related priorities are keeping my attention, but I hope to look into this soon.

**Comment by lgpage** [comment]
Should be fixed by #44
