### ISSUE TITLE
Failed to load extension error

### ISSUE THREAD

**Issue by psychemedia** [lgpage/nbtutor#34]
Running `nbtutor` in a [recent Jupyter notebooks build](https://mybinder.org/v2/gh/psychemedia/showntell/computing?filepath=index_computing.ipynb) gives a `Failed to load extension - Error: Script error for "nbextensions/nbtutor/js/nbtutor.min"` error?

**Comment by lgpage** [comment]
@psychemedia can you check if updating your ``postBuild`` file to include the ``--sys-prefix`` tag works? Along the lines of:
```
jupyter-nbextension install --sys-prefix --py nbtutor
jupyter-nbextension enable --sys-prefix --py nbtutor
```

**Comment by psychemedia** [comment]
@lgpage ah... prefix wasn't set - is now, which means the extension loads.

Thanks for that - sorry for not spotting it. 

And thanks for the extension:-)

--tony
