### ISSUE TITLE
Are you still maintaining this project?

### ISSUE THREAD

**Issue by Naereen** [lgpage/nbtutor#41]
Hello there,
I suspect this project is now unmaintained, last commit was in 2016...
@lgpage are you still maintaining this project?
It's very interesting and it would be valuable to keep it running! Thanks in advance!
I'm willing to *try to* help it, but I'm not feeling confident it taking the full responsibility.
Regards from France, @Naereen

**Comment by lgpage** [comment]
@Naereen this repo has been a bit neglected, I am sorry :(
I have slowly been re-writing the code so that I can more easily maintain it in the future and I will make a concerted effort the next two week to get this pushed to source

**Comment by Naereen** [comment]
Hi @lgpage,
Please don't apologize! We all mainly do open source on our free time, for free money, for fun, so there is no pressure!
I was asking out of curiosity, to know if opening other issues would be helpful or not.
Don't force yourself on a deadline, or at least please don't interpret my question as any form of pressure!

Now that I clarified that, if you want help you can ask, I can try the latest version or at least read your code before merging a PR, if you want an external point of view!
Regards, have a nice Sunday :sun_with_face: !

**Comment by lgpage** [comment]
Hi @Naereen 
Please feel free to open new tickets if you find new issues, we will need to go through each one with the new code and see if the issue still occurs.
The re-write so close to finished (I just have a few bugs to squash and loose ends to tie up), so I am using your questions more as a good excuse for motivation to finish it :P 
Your offer to helps is greatly appreciated, it will be more than helpful to have another set of eyes on the code, both in terms of reviewing the PR and trying out the latest version :)
