### ISSUE TITLE
Errors running nbtutor from repo in Classic notebook

### ISSUE THREAD

**Issue by psychemedia** [lgpage/nbtutor#48]
Hi

Running the current dev version installed from the repo, I'm not seeing `nbtutor` in the classic notebook UI.

![image](https://user-images.githubusercontent.com/82988/135295326-5416bd9e-f88d-4100-b72c-1e12021c999d.png)

**Comment by lgpage** [comment]
As mentioned in the [Readme](https://github.com/lgpage/nbtutor#install) the pre-built JavaScript and CSS is not committed to source, so installing directly from the repo won't work.

Please see the [Development](https://github.com/lgpage/nbtutor/blob/main/DEVELOPMENT.md) page for more information on how to build the JavaScript and CSS and install locally
